### ISSUE TITLE
"UnityEngine.AsyncOperation not awaitable"

### ISSUE THREAD

**Issue by scvnathan** [zsaladin/Asyncoroutine#1]
Hello, I'm having an issue awaiting the AsyncOperation from UnityWebRequest:

```
var req = new UnityWebRequest(someUrl);
await req.Send();
```

Is there a way to await a UnityEngine.AsyncOperation object?

Thanks!
(And thanks for this project, its pretty handy!)

**Comment by zsaladin** [comment]
Hello
Thank you for your feedback.

I tested code below. And It worked.
```C#
var req = new UnityWebRequest("https://google.com"); 
req.downloadHandler = new DownloadHandlerBuffer();
AsyncOperation asyncOperation = await req.Send();

Debug.Log(asyncOperation.progress);
Debug.Log(req.downloadHandler.text);
```
Could you update the library? Your version might be outdated.
If it cannot solve the problem, please provide me the error messages.

Thank you.

**Comment by scvnathan** [comment]
My version was out of date. Also it looks like it might also be an issue with Jetbrains Rider. I can get it to compile now, but the editor still reports that error ("UnityEngine.AsyncOperation not awaitable").

👍
